version: '3.2'
services:
  database:
    build:
      context: ./database
    image: spotify/database:latest
    ports:
      - 5432:5432
    container_name: database
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
