spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify
    username: spotify
    password: spotifypass
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
server:
  port: 8080
  servlet:
    context-path: /demo
